### ISSUE TITLE
Frappe Erpnext Version Requirements

### ISSUE THREAD

**Issue by joshreeder** [pipech/frappe-metabase#2]
Does this require version 12? upon installing in version 11 I got this error:

```
Installing metabase_integration...
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/joshreeder/Dev/frappe-v11/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/joshreeder/Dev/frappe-v11/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/joshreeder/Dev/frappe-v11/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/joshreeder/Dev/frappe-v11/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/joshreeder/Dev/frappe-v11/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/joshreeder/Dev/frappe-v11/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/joshreeder/Dev/frappe-v11/env/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/commands/site.py", line 168, in install_app
    _install_app(app, verbose=context.verbose)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/installer.py", line 145, in install_app
    sync_for(name, force=True, sync_everything=True, verbose=verbose, reset_permissions=True)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/model/sync.py", line 56, in sync_for
    reset_permissions=reset_permissions, for_sync=True)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/modules/import_file.py", line 65, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/modules/import_file.py", line 100, in import_doc
    doc = frappe.get_doc(docdict)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/__init__.py", line 734, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/model/document.py", line 69, in get_doc
    return controller(*args, **kwargs)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/model/document.py", line 113, in __init__
    super(Document, self).__init__(kwargs)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/model/base_document.py", line 54, in __init__
    self.update(d)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/model/base_document.py", line 77, in update
    self.set(key, value)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/model/base_document.py", line 124, in set
    self.extend(key, value)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/model/base_document.py", line 161, in extend
    self.append(key, v)
  File "/Users/joshreeder/Dev/frappe-v11/apps/frappe/frappe/model/base_document.py", line 155, in append
    self.name, str(type(value))[1:-1], value)
ValueError: Document for field "field_order" attached to child table of "Metabase Dashboard" must be a dict or BaseDocument, not class 'str' (dashboard_name)
```

**Comment by pipech** [comment]
Again, really sorry for 4 months late reply.

I can replicate this error on version 11.

After removing `field_order` on doctype json file it's seems to solve the problems.

I think `field_order` just got introduce in version 12.

https://github.com/pipech/frappe-metabase/blob/b1a901bc196dc3aeb766c1955a11cc9b65f19941/metabase_integration/metabase_integration/doctype/metabase_settings/metabase_settings.json#L6-L11

https://github.com/pipech/frappe-metabase/blob/b1a901bc196dc3aeb766c1955a11cc9b65f19941/metabase_integration/metabase_integration/doctype/metabase_dashboard/metabase_dashboard.json#L7-L17
