### ISSUE TITLE
Why is there no development for v13

### ISSUE THREAD

**Issue by dawoodjee** [pipech/frappe-metabase#3]
Hello @pipech 

Long time! This is a very promising project, I just saw it and I'm wondering why there hasn't been developed for 2 years

I think even with frappe's Dashboard features this project remains relevant

**Comment by arahimfahim40** [comment]
Yes, I don't this works on V13,  I tried it, but doesn't work. Hopefully they can work for it more.

**Comment by dawoodjee** [comment]
@arahimfahim40 its only one guy working on this. Very impressive, if I may add. We really should support anyway possible

**Comment by arahimfahim40** [comment]
hey btw, I am trying to integrate this into ERPNext v13.6 but I'm getting this error: "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 187: invalid start byte". If you know how to solve this, it will be much appreciated!

I checked the console and this was the full tracebok:
```
`Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
request.js:387 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1172, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 32, in getpage
    doc = get(page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 15, in get
    page.load_assets()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/page/page.py", line 113, in load_assets
    self.script = render_include(f.read())
  File "/home/frappe/frappe-bench/env/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 187: invalid start byte

/socket.io/?EIO=3&transport=polling&t=NgDWDmv:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)`
```
